# Generated by Django 5.2.5 on 2026-07-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='optout_public_chat',
            field=models.BooleanField(default=False),
        ),
    ]
